Feature/serde support
IGI-111/bktree pull request #1
Opened 2023-03-04 04:15 UTC by johnDeSilencio

This PR creates the new trait `Distance` which has one method with the following signature:
```rust
pub trait Distance<T: ?Sized> {
    fn distance(&self, a: &T, b: &T) -> isize;
}
```
The functions `hamming_distance()` and `levenshtein_distance()` are refactored to `impl` the Distance trait for the new structs `HammingDistance` and `LevenshteinDistance`. These structs do not hold state, but can be passed in as type parameters to create `BkTree` objects with known size at compile time, e.g.
```rust
let mut bk = BkTree::new(HammingDistance);
// ...
let mut bk = BkTree::new(LevenshteinDistance);
```

The remainder of the refactor changes consist in refactoring `BkTree` to accept the second type parameter and fixing the unit tests accordingly.

Finally, this PR adds the `serde-support` feature to enable serializing and deserializing `BkTree` objects for those that would desire to do so. 

Note that this PR leans heavily on the work done by @eugene-bulkin in the [rust-bk-tree](https://github.com/eugene-bulkin/rust-bk-tree) crate as well as the work on an [outstanding PR to support serialization](https://github.com/eugene-bulkin/rust-bk-tree/pull/12) in that crate by @stnbu

2023-03-16 17:55 UTC, johnDeSilencio commented
@IGI-111 Looking forward to your feedback on this!

2023-03-16 18:40 UTC, IGI-111 requested changes
I like the idea, I thought about an enum alternative or straight up serializing the boxed fn but this way of doing it conserves the extensibility without being too magical.

2023-03-16 18:40 UTC, IGI-111 commented on src/lib.rs
> +            dist: dist,
```suggestion
            dist,
```

2023-03-16 18:40 UTC, IGI-111 commented on src/lib.rs
> +    pub fn new(dist: D) -> BkTree<T, D> {
```suggestion
    pub fn new(dist: D) -> Self {
```

2023-03-16 18:40 UTC, IGI-111 commented on src/lib.rs
> +        BkTree {
```suggestion
        Self {
```

2023-03-17 06:11 UTC, johnDeSilencio commented
I also tried the enum approach at first but with no luck, so I ended up copying what @stnbu did in the other BK Tree crate. I'm still new to Rust development and serializing Boxed Fn's definitely seems magical to me :smile: Glad you think the trait generics are a good tradeoff.

I've incorporated your suggestions in the most recent commits. If there's anything else you think this PR needs, feel free to let me know! Thanks for maintaining this awesome crate

2023-03-22 03:11 UTC, johnDeSilencio commented
@IGI-111 Ready for re-review

2023-03-23 14:44 UTC, merged